"""Add display names to RepostPair

Revision ID: 864ee5cb4e60
Revises: b09782368c08
Create Date: 2026-04-17 21:02:38.871288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '864ee5cb4e60'
down_revision: Union[str, None] = 'b09782368c08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repost_pairs', sa.Column('source_display', sa.String(), nullable=True))
    op.add_column('repost_pairs', sa.Column('destination_display', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repost_pairs', 'destination_display')
    op.drop_column('repost_pairs', 'source_display')
    # ### end Alembic commands ###
