"""add_schedule_interval

Revision ID: 97e0d9f12ec9
Revises: 08bc12966c91
Create Date: 2026-02-14 12:46:12.043582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97e0d9f12ec9'
down_revision: Union[str, None] = '08bc12966c91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repost_pairs', sa.Column('schedule_interval', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repost_pairs', 'schedule_interval')
    # ### end Alembic commands ###
