"""Add is_protected flag

Revision ID: b09782368c08
Revises: b4g2c3d5e7f8
Create Date: 2026-04-17 18:50:47.540739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b09782368c08'
down_revision: Union[str, None] = 'b4g2c3d5e7f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('system_settings',
    # sa.Column('key', sa.String(), nullable=False),
    # sa.Column('value', sa.String(), nullable=False),
    # sa.PrimaryKeyConstraint('key')
    # )
    # op.add_column('repost_pairs', sa.Column('next_allowed_post_at', sa.DateTime(), nullable=True))
    op.add_column('repost_pairs', sa.Column('is_protected', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    # op.alter_column('repost_pairs', 'loop_history',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=False,
    #            existing_server_default=sa.text('0'))
    # op.alter_column('repost_pairs', 'alerted_3d',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=False,
    #            existing_server_default=sa.text('0'))
    # op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    # op.add_column('users', sa.Column('is_premium', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    # op.add_column('users', sa.Column('premium_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'premium_until')
    op.drop_column('users', 'is_premium')
    op.drop_column('users', 'is_admin')
    op.alter_column('repost_pairs', 'alerted_3d',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('repost_pairs', 'loop_history',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_column('repost_pairs', 'is_protected')
    op.drop_column('repost_pairs', 'next_allowed_post_at')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
